sia-demo
icepack/icepack pull request #62
Opened 2020-10-16 22:40 UTC by jabadge

I updated the penalty term of the shallow_ice model. I also added a new demo using it to model a synthetic ice sheet. Because this demo is simpler than all but the 00-meshes-functions demo, I rearranged the order of the demos and adjusted the wording of the synthetic-ice-shelf demo to reflect this new ordering.

2020-10-19 18:51 UTC, danshapero commented
So it looks like you're getting a test failure because now you need to pass the thickness when calculating the scale functional as well as the velocity. The line that's causing the test failure is [here](https://github.com/icepack/icepack/blob/b1552d1e04469f8545845b88cf2ae91735f3914f/test/shallow_ice_test.py#L111). You could just add `thickness=h` as another keyword argument to that function call to fix it.

After that's fixed, we'll get another failure because the test that you wrote before assumed very minimal smoothing and thus expected an asymptotic convergence rate close to 1. Now as we've both learned from you writing this demo, using that little smoothing is impractical once you actually try to do anything interesting. But it also means that we're no longer solving the equations exactly and so we shouldn't expect the same convergence rate. You can change [this line](https://github.com/icepack/icepack/blob/b1552d1e04469f8545845b88cf2ae91735f3914f/test/shallow_ice_test.py#L118) to assert that the slope is greater than 0 instead of 0.9. We can think of a better testing strategy later but this is fine for now.

I've made some more specific comments as reviews, but those are minor and all together this looks great!

2020-10-19 19:02 UTC, danshapero requested changes
Mostly minor things, there's some wordage left over from the ice shelf demo that should say "ice sheet" instead, and a handful of calls to `interpolate` are redundant.

2020-10-19 19:02 UTC, danshapero commented on demo/01-synthetic-ice-sheet.ipynb
> +    "As we'll show later on in this demo, passing arguments by keyword makes it possible to swap out components of the model physics for your own customized versions.\n",
This should be changed from "later on in this demo" to "in the next demo".

2020-10-19 19:02 UTC, danshapero commented on demo/01-synthetic-ice-sheet.ipynb
> +    "contours = icepack.plot.tricontourf(firedrake.interpolate(s,Q), 40, axes=axes, cmap='magma')\n",
This interpolate call should be unnecessary too.

2020-10-21 16:25 UTC, jabadge commented
@danshapero Thanks for these edits! I made your recommended changes to the ice sheet demo and shallow ice test.

2020-10-21 22:26 UTC, danshapero approved these changes

2020-10-21 22:27 UTC, merged